# GitHub Sponsors configuration for FlowGit
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

ko_fi: longgoll
custom: ['https://github.com/longgoll/flow-git#--support-the-project--%E1%BB%A7ng-h%E1%BB%99-d%E1%BB%B1-%C3%A1n']
